#!/usr/bin/python
#-*- coding: utf-8 -*-
require_once("../../../wp-load.php")
header("Content-Type: text/html; charset="+get_bloginfo("charset"))
print("<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml" ")
language_attributes()
print(">\n<head>\n<meta http-equiv="Content-Type" content="")
bloginfo("html_type")
print("; charset=")
print(get_option("blog_charset"))
print("" />\n<title>")
_e("Rich Editor Help")
print("</title>\n<script type="text/javascript" src="tiny_mce_popup.js?ver=358-20121205"></script>\n")
wp_admin_css("wp-admin", True)
print("<style type="text/css">\n	body {\n		min-width: 0;\n	}\n	#wphead {\n		font-size: 80%;\n		border-top: 0;\n		color: #555;\n		background-color: #f1f1f1;\n	}\n	#wphead h1 {\n		font-size: 24px;\n		color: #555;\n		margin: 0;\n		padding: 10px;\n	}\n	#tabs {\n		padding: 15px 15px 3px;\n		background-color: #f1f1f1;\n		border-bottom: 1px solid #dfdfdf;\n		margin: 0;\n	}\n	#tabs li {\n		display: inline;\n	}\n	#tabs a.current {\n		background-color: #fff;\n		border-color: #dfdfdf;\n		border-bottom-color: #fff;\n		color: #d54e21;\n	}\n	#tabs a {\n		color: #2583AD;\n		padding: 6px;\n		border-width: 1px 1px 0;\n		border-style: solid solid none;\n		border-color: #f1f1f1;\n		text-decoration: none;\n	}\n	#tabs a:hover {\n		color: #d54e21;\n	}\n	.wrap h2 {\n		border-bottom-color: #dfdfdf;\n		color: #555;\n		margin: 5px 0;\n		padding: 0;\n		font-size: 18px;\n	}\n	#user_info {\n		right: 5%;\n		top: 5px;\n	}\n	h3 {\n		font-size: 1.1em;\n		margin-top: 10px;\n		margin-bottom: 0px;\n	}\n	#flipper {\n		margin: 0;\n		padding: 5px 20px 10px;\n		background-color: #fff;\n		border-left: 1px solid #dfdfdf;\n		border-bottom: 1px solid #dfdfdf;\n	}\n	* html {\n        overflow-x: hidden;\n        overflow-y: scroll;\n    }\n	#flipper div p {\n		margin-top: 0.4em;\n		margin-bottom: 0.8em;\n		text-align: justify;\n	}\n	th {\n		text-align: center;\n	}\n	.top th {\n		text-decoration: underline;\n	}\n	.top .key {\n		text-align: center;\n		width: 5em;\n	}\n	.top .action {\n		text-align: left;\n	}\n	.align {\n		border-left: 3px double #333;\n		border-right: 3px double #333;\n	}\n	.keys {\n		margin-bottom: 15px;\n		width: 100%;\n		border: 0 none;\n	}\n	.keys p {\n		display: inline-block;\n		margin: 0px;\n		padding: 0px;\n	}\n	.keys .left { text-align: left; }\n	.keys .center { text-align: center; }\n	.keys .right { text-align: right; }\n	td b {\n		font-family: "Times New Roman" Times serif;\n	}\n	#buttoncontainer {\n		text-align: center;\n		margin-bottom: 20px;\n	}\n	#buttoncontainer a, #buttoncontainer a:hover {\n		border-bottom: 0px;\n	}\n	.macos .win,\n	.windows .mac {\n		display: none;\n	}\n</style>\n")
if is_rtl():
  print("<style type="text/css">\n	#wphead, #tabs {\n		padding-left: auto;\n		padding-right: 15px;\n	}\n	#flipper {\n		margin: 5px 0 3px 10px;\n	}\n	.keys .left, .top, .action { text-align: right; }\n	.keys .right { text-align: left; }\n	td b { font-family: Tahoma, "Times New Roman", Times, serif }\n</style>\n")
print("</head>\n<body class="windows wp-core-ui">\n<script type="text/javascript">\nif ( tinymce.isMac )\n	document.body.className = document.body.className.replace(/windows/, 'macos');\n</script>\n\n<ul id="tabs">\n	<li><a id="tab1" href="javascript:flipTab(1)" title="")
esc_attr_e("Basics of Rich Editing")
print("" accesskey="1" class="current">")
_e("Basics")
print("</a></li>\n	<li><a id="tab2" href="javascript:flipTab(2)" title="")
esc_attr_e("Advanced use of the Rich Editor")
print("" accesskey="2">")
_e("Advanced")
print("</a></li>\n	<li><a id="tab3" href="javascript:flipTab(3)" title="")
esc_attr_e("Hotkeys")
print("" accesskey="3">")
_e("Hotkeys")
print("</a></li>\n	<li><a id="tab4" href="javascript:flipTab(4)" title="")
esc_attr_e("About the software")
print("" accesskey="4">")
_e("About")
print("</a></li>\n</ul>\n\n<div id="flipper" class="wrap">\n\n<div id="content1">\n	<h2>")
_e("Rich Editing Basics")
print("</h2>\n	<p>")
_e("<em>Rich editing</em>, also called WYSIWYG for What You See Is What You Get, means your text is formatted as you type. The rich editor creates HTML code behind the scenes while you concentrate on writing. Font styles, links and images all appear approximately as they will on the internet.")
print("</p>\n	<p>")
_e("WordPress includes a rich HTML editor that works well in all major web browsers used today. However editing HTML is not the same as typing text. Each web page has two major components: the structure, which is the actual HTML code and is produced by the editor as you type, and the display, that is applied to it by the currently selected WordPress theme and is defined in style.css. WordPress is producing valid XHTML 1.0 which means that inserting multiple line breaks (BR tags) after a paragraph would not produce white space on the web page. The BR tags will be removed as invalid by the internal HTML correcting functions.")
print("</p>\n	<p>")
_e("While using the editor, most basic keyboard shortcuts work like in any other text editor. For example: Shift+Enter inserts line break, Ctrl+C = copy, Ctrl+X = cut, Ctrl+Z = undo, Ctrl+Y = redo, Ctrl+A = select all, etc. (on Mac use the Command key instead of Ctrl). See the Hotkeys tab for all available keyboard shortcuts.")
print("</p>\n    <p>")
_e("If you do not like the way the rich editor works, you may turn it off from Your Profile submenu, under Users in the admin menu.")
print("</p>\n</div>\n\n<div id="content2" class="hidden">\n	<h2>")
_e("Advanced Rich Editing")
print("</h2>\n	<h3>")
_e("Images and Attachments")
print("</h3>\n	<p>")
_e("There is a button in the editor toolbar for inserting images that are already hosted somewhere on the internet. If you have a URL for an image, click this button and enter the URL in the box which appears.")
print("</p>\n	<p>")
_e("If you need to upload an image or another media file from your computer, you can use the Media Library button above the editor. The media library will attempt to create a thumbnail-sized copy from each uploaded image. To insert your image into the post, first click on the thumbnail to reveal a menu of options. When you have selected the options you like, click "Insert into Post" and your image or file will appear in the post you are editing.")
print("</p>\n	<h3>")
_e("HTML in the Rich Editor")
print("</h3>\n	<p>")
_e("Any HTML entered directly into the rich editor will show up as text when the post is viewed. What you see is what you get. When you want to include HTML elements that cannot be generated with the toolbar buttons, you must enter it by hand in the Text editor. Examples are tables and &lt;code&gt;. To do this, click the Text tab and edit the code, then switch back to Visual mode. If the code is valid and understood by the editor, you should see it rendered immediately.")
print("</p>\n	<h3>")
_e("Pasting in the Rich Editor")
print("</h3>\n	<p>")
_e("When pasting content from another web page the results can be inconsistent and depend on your browser and on the web page you are pasting from. The editor tries to correct any invalid HTML code that was pasted, but for best results try using the Text tab or one of the paste buttons that are on the second row. Alternatively try pasting paragraph by paragraph. In most browsers to select one paragraph at a time, triple-click on it.")
print("</p>\n	<p>")
_e("Pasting content from another application, like Word or Excel, is best done with the Paste from Word button on the second row, or in Text mode.")
print("</p>\n</div>\n\n<div id="content3" class="hidden">\n	<h2>")
_e("Writing at Full Speed")
print("</h2>\n    <p>")
_e("Rather than reaching for your mouse to click on the toolbar, use these access keys. Windows and Linux use Ctrl + letter. Macintosh uses Command + letter.")
print("</p>\n\n	<table class="keys">\n		<tr class="top"><th class="key center">")
_e("Letter")
print("</th><th class="left">")
_e("Action")
print("</th><th class="key center">")
_e("Letter")
print("</th><th class="left">")
_e("Action")
print("</th></tr>\n		<tr><th>c</th><td>")
_e("Copy")
print("</td><th>v</th><td>")
_e("Paste")
print("</td></tr>\n		<tr><th>a</th><td>")
_e("Select all")
print("</td><th>x</th><td>")
_e("Cut")
print("</td></tr>\n		<tr><th>z</th><td>")
_e("Undo")
print("</td><th>y</th><td>")
_e("Redo")
print("</td></tr>\n\n		<tr><th>b</th><td>")
_e("Bold")
print("</td><th>i</th><td>")
_e("Italic")
print("</td></tr>\n		<tr><th>u</th><td>")
_e("Underline")
print("</td><th>1</th><td>")
_e("Heading 1")
print("</td></tr>\n		<tr><th>2</th><td>")
_e("Heading 2")
print("</td><th>3</th><td>")
_e("Heading 3")
print("</td></tr>\n		<tr><th>4</th><td>")
_e("Heading 4")
print("</td><th>5</th><td>")
_e("Heading 5")
print("</td></tr>\n		<tr><th>6</th><td>")
_e("Heading 6")
print("</td><th>9</th><td>")
_e("Address")
print("</td></tr>\n	</table>\n\n	<p>")
_e("The following shortcuts use different access keys: Alt + Shift + letter.")
print("</p>\n	<table class="keys">\n		<tr class="top"><th class="key center">")
_e("Letter")
print("</th><th class="left">")
_e("Action")
print("</th><th class="key center">")
_e("Letter")
print("</th><th class="left">")
_e("Action")
print("</th></tr>\n		<tr><th>n</th><td>")
_e("Check Spelling")
print("</td><th>l</th><td>")
_e("Align Left")
print("</td></tr>\n		<tr><th>j</th><td>")
_e("Justify Text")
print("</td><th>c</th><td>")
_e("Align Center")
print("</td></tr>\n		<tr><th>d</th><td><span style="text-decoration: line-through;">")
_e("Strikethrough")
print("</span></td><th>r</th><td>")
_e("Align Right")
print("</td></tr>\n		<tr><th>u</th><td><strong>&bull;</strong> ")
_e("List")
print("</td><th>a</th><td>")
_e("Insert link")
print("</td></tr>\n		<tr><th>o</th><td>1. ")
_e("List")
print("</td><th>s</th><td>")
_e("Remove link")
print("</td></tr>\n		<tr><th>q</th><td>")
_e("Quote")
print("</td><th>m</th><td>")
_e("Insert Image")
print("</td></tr>\n		<tr><th>w</th><td>")
_e("Distraction Free Writing mode")
print("</td><th>t</th><td>")
_e("Insert More Tag")
print("</td></tr>\n		<tr><th>p</th><td>")
_e("Insert Page Break tag")
print("</td><th>h</th><td>")
_e("Help")
print("</td></tr>\n	</table>\n\n	<p style="padding: 15px 10px 10px;">")
_e("Editor width in Distraction Free Writing mode:")
print("</p>\n	<table class="keys">\n		<tr><th><span class="win">Alt +</span><span class="mac">Ctrl +</span></th><td>")
_e("Wider")
print("</td>\n			<th><span class="win">Alt -</span><span class="mac">Ctrl -</span></th><td>")
_e("Narrower")
print("</td></tr>\n		<tr><th><span class="win">Alt 0</span><span class="mac">Ctrl 0</span></th><td>")
_e("Default width")
print("</td><th></th><td></td></tr>\n	</table>\n</div>\n\n<div id="content4" class="hidden">\n	<h2>")
_e("About TinyMCE")
print("</h2>\n\n    <p>")
_e("Version:")
print(" <span id="version"></span> (<span id="date"></span>)</p>\n	<p>")
printf(__("TinyMCE is a platform independent web based Javascript HTML WYSIWYG editor released as Open Source under %sLGPL</a>	by Moxiecode Systems AB. It has the ability to convert HTML TEXTAREA fields or other HTML elements to editor instances."), "<a href=""+home_url("/wp-includes/js/tinymce/license.txt")+"" target="_blank" title=""+esc_attr__("GNU Library General Public License")+"">")
print("</p>\n	<p>")
_e("Copyright &copy; 2003-2011, <a href="http://www.moxiecode.com" target="_blank">Moxiecode Systems AB</a>, All rights reserved.")
print("</p>\n	<p>")
_e("For more information about this software visit the <a href="http://tinymce.com" target="_blank">TinyMCE website</a>.")
print("</p>\n\n	<div id="buttoncontainer">\n		<a href="http://www.moxiecode.com" target="_blank"><img src="themes/advanced/img/gotmoxie.png" alt="")
esc_attr_e("Got Moxie?")
print("" style="border: 0" /></a>\n	</div>\n\n</div>\n</div>\n\n<div class="mceActionPanel">\n	<div style="margin: 8px auto; text-align: center;padding-bottom: 10px;">\n		<input type="button" id="cancel" name="cancel" value="")
esc_attr_e("Close")
print("" title="")
esc_attr_e("Close")
print("" onclick="tinyMCEPopup.close();" />\n	</div>\n</div>\n<script type="text/javascript">\n	function d(id) { return document.getElementById(id); }\n\n	function flipTab(n) {\n		var i, c, t;\n\n		for ( i = 1; i <= 4; i++ ) {\n			c = d('content'+i.toString());\n			t = d('tab'+i.toString());\n			if ( n == i ) {\n				c.className = '';\n				t.className = 'current';\n			} else {\n				c.className = 'hidden';\n				t.className = '';\n			}\n		}\n	}\n\n    tinyMCEPopup.onInit.add(function() {\n        var win = tinyMCEPopup.getWin();\n\n		d('version').innerHTML = tinymce.majorVersion + "." + tinymce.minorVersion;\n        d('date').innerHTML = tinymce.releaseDate;\n\n		if ( win.fullscreen && win.fullscreen.settings.visible ) {\n			d('content1').className = 'hidden';\n			d('tabs').className = 'hidden';\n			d('content3').className = 'dfw';\n		}\n    });\n</script>\n</body>\n</html>\n")
