#!/usr/bin/python
#-*- coding: utf-8 -*-
_deprecated_file(sprintf(__("Theme without %1$s"), basename("wop/wp-includes/theme-compat/sidebar.php")), "3.0", , sprintf(__("Please include a %1$s template in your theme."), basename("wop/wp-includes/theme-compat/sidebar.php")))
print("	<div id="sidebar" role="complementary">\n		<ul>\n			")
if !function_exists("dynamic_sidebar")||!dynamic_sidebar():
  print("			<li>\n				")
  get_search_form()
  print("			</li>\n\n			<!-- Author information is disabled per default. Uncomment and fill in your details if you want to use it.\n			<li><h2>")
  _e("Author")
  print("</h2>\n			<p>A little something about you, the author. Nothing lengthy, just an overview.</p>\n			</li>\n			-->\n\n			")
  if is_404()||is_category()||is_day()||is_month()||is_year()||is_search()||is_paged():
    print(" <li>\n\n			")
    if is_404():
      print("			")
    elif is_category():
      print("			<p>")
      printf(__("You are currently browsing the archives for the %s category."), single_cat_title("", False))
      print("</p>\n\n			")
    elif is_day():
      print("			<p>")
      printf(__("You are currently browsing the <a href="%1$s/">%2$s</a> blog archives for the day %3$s."), get_bloginfo("url"), get_bloginfo("name"), get_the_time(__("l, F jS, Y")))
      print("</p>\n\n			")
    elif is_month():
      print("			<p>")
      printf(__("You are currently browsing the <a href="%1$s/">%2$s</a> blog archives for %3$s."), get_bloginfo("url"), get_bloginfo("name"), get_the_time(__("F, Y")))
      print("</p>\n\n			")
    elif is_year():
      print("			<p>")
      printf(__("You are currently browsing the <a href="%1$s/">%2$s</a> blog archives for the year %3$s."), get_bloginfo("url"), get_bloginfo("name"), get_the_time("Y"))
      print("</p>\n\n			")
    elif is_search():
      print("			<p>")
      printf(__("You have searched the <a href="%1$s/">%2$s</a> blog archives for <strong>&#8216;%3$s&#8217;</strong>. If you are unable to find anything in these search results, you can try one of these links."), get_bloginfo("url"), get_bloginfo("name"), esc_html(get_search_query()))
      print("</p>\n\n			")
    elif isset(_GET["paged"])&&!empty(_GET["paged"]):
      print("			<p>")
      printf(__("You are currently browsing the <a href="%1$s/">%2$s</a> blog archives."), get_bloginfo("url"), get_bloginfo("name"))
      print("</p>\n\n			")
    print("\n			</li>\n		")
  print("		</ul>\n		<ul role="navigation">\n			")
  wp_list_pages("title_li=<h2>"+__("Pages")+"</h2>")
  print("\n			<li><h2>")
  _e("Archives")
  print("</h2>\n				<ul>\n				")
  wp_get_archives({"type":"monthly"})
  print("				</ul>\n			</li>\n\n			")
  wp_list_categories({"show_count":1, "title_li":"<h2>"+__("Categories")+"</h2>"})
  print("		</ul>\n		<ul>\n			")
  if is_home()||is_page():
    print("				")
    wp_list_bookmarks()
    print("\n				<li><h2>")
    _e("Meta")
    print("</h2>\n				<ul>\n					")
    wp_register()
    print("					<li>")
    wp_loginout()
    print("</li>\n					<li><a href="http://validator.w3.org/check/referer" title="")
    esc_attr_e("This page validates as XHTML 1.0 Transitional")
    print("">")
    _e("Valid <abbr title="eXtensible HyperText Markup Language">XHTML</abbr>")
    print("</a></li>\n					<li><a href="http://gmpg.org/xfn/"><abbr title="")
    esc_attr_e("XHTML Friends Network")
    print("">")
    _e("XFN")
    print("</abbr></a></li>\n					<li><a href="http://wordpress.org/" title="")
    esc_attr_e("Powered by WordPress, state-of-the-art semantic personal publishing platform.")
    print("">WordPress</a></li>\n					")
    wp_meta()
    print("				</ul>\n				</li>\n			")
  print("\n			")
print("		</ul>\n	</div>\n")
