#!/usr/bin/python
#-*- coding: utf-8 -*-
get_header()
print("\n		<section id="primary">\n			<div id="content" role="main">\n\n			")
if have_posts():
  print("\n				")
  the_post()
  print("\n				<header class="page-header">\n					<h1 class="page-title author">")
  printf(__("Author Archives: %s", "twentyeleven"), "<span class="vcard"><a class="url fn n" href=""+esc_url(get_author_posts_url(get_the_author_meta("ID")))+"" title=""+esc_attr(get_the_author())+"" rel="me">"+get_the_author()+"</a></span>")
  print("</h1>\n				</header>\n\n				")
  rewind_posts()
  print("\n				")
  twentyeleven_content_nav("nav-above")
  print("\n				")
  if get_the_author_meta("description"):
    print("				<div id="author-info">\n					<div id="author-avatar">\n						")
    print(get_avatar(get_the_author_meta("user_email"), apply_filters("twentyeleven_author_bio_avatar_size", 60)))
    print("					</div><!-- #author-avatar -->\n					<div id="author-description">\n						<h2>")
    printf(__("About %s", "twentyeleven"), get_the_author())
    print("</h2>\n						")
    the_author_meta("description")
    print("					</div><!-- #author-description	-->\n				</div><!-- #author-info -->\n				")
  print("\n				")
  print("				")
  while :
    the_post()
    print("\n					")
    get_template_part("content", get_post_format())
    print("\n				")
  print("\n				")
  twentyeleven_content_nav("nav-below")
  print("\n			")
else:
  print("\n				<article id="post-0" class="post no-results not-found">\n					<header class="entry-header">\n						<h1 class="entry-title">")
  _e("Nothing Found", "twentyeleven")
  print("</h1>\n					</header><!-- .entry-header -->\n\n					<div class="entry-content">\n						<p>")
  _e("Apologies, but no results were found for the requested archive. Perhaps searching will help find a related post.", "twentyeleven")
  print("</p>\n						")
  get_search_form()
  print("					</div><!-- .entry-content -->\n				</article><!-- #post-0 -->\n\n			")
print("\n			</div><!-- #content -->\n		</section><!-- #primary -->\n\n")
get_sidebar()
get_footer()
