#!/usr/bin/python
#-*- coding: utf-8 -*-
print("\n<article id="post-")
the_ID()
print("" ")
post_class()
print(">\n	<header class="entry-header">\n		<h1 class="entry-title">")
the_title()
print("</h1>\n\n		")
if "post"==get_post_type():
  print("		<div class="entry-meta">\n			")
  twentyeleven_posted_on()
  print("		</div><!-- .entry-meta -->\n		")
print("	</header><!-- .entry-header -->\n\n	<div class="entry-content">\n		")
the_content()
print("		")
wp_link_pages({"before":"<div class="page-link"><span>"+__("Pages:", "twentyeleven")+"</span>", "after":"</div>"})
print("	</div><!-- .entry-content -->\n\n	<footer class="entry-meta">\n		")
categories_list = get_the_category_list(__(", ", "twentyeleven"))
tag_list = get_the_tag_list("", __(", ", "twentyeleven"))
if ""!=tag_list:
  utility_text = __("This entry was posted in %1$s and tagged %2$s by <a href="%6$s">%5$s</a>. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.", "twentyeleven")
elif ""!=categories_list:
  utility_text = __("This entry was posted in %1$s by <a href="%6$s">%5$s</a>. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.", "twentyeleven")
else:
  utility_text = __("This entry was posted by <a href="%6$s">%5$s</a>. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.", "twentyeleven")
printf(utility_text, categories_list, tag_list, esc_url(get_permalink()), the_title_attribute("echo=0"), get_the_author(), esc_url(get_author_posts_url(get_the_author_meta("ID"))))
print("		")
edit_post_link(__("Edit", "twentyeleven"), "<span class="edit-link">", "</span>")
print("\n		")
if get_the_author_meta("description")&&!function_exists("is_multi_author")||is_multi_author():
  print("\n		<div id="author-info">\n			<div id="author-avatar">\n				")
  print(get_avatar(get_the_author_meta("user_email"), apply_filters("twentyeleven_author_bio_avatar_size", 68)))
  print("			</div><!-- #author-avatar -->\n			<div id="author-description">\n				<h2>")
  printf(__("About %s", "twentyeleven"), get_the_author())
  print("</h2>\n				")
  the_author_meta("description")
  print("				<div id="author-link">\n					<a href="")
  print(esc_url(get_author_posts_url(get_the_author_meta("ID"))))
  print("" rel="author">\n						")
  printf(__("View all posts by %s <span class="meta-nav">&rarr;</span>", "twentyeleven"), get_the_author())
  print("					</a>\n				</div><!-- #author-link	-->\n			</div><!-- #author-description -->\n		</div><!-- #author-info -->\n		")
print("	</footer><!-- .entry-meta -->\n</article><!-- #post-")
the_ID()
print(" -->\n")
