#!/usr/bin/python
#-*- coding: utf-8 -*-
require_once("./admin.php")
title = __("About")
display_versionexplode("-", wp_version)
include(ABSPATH+"wp-admin/admin-header.php")
print("<div class="wrap about-wrap">\n\n<h1>")
printf(__("Welcome to WordPress %s"), display_version)
print("</h1>\n\n<div class="about-text">")
printf(__("Thank you for updating to the latest version! WordPress %s is more polished and enjoyable than ever before. We hope you like it."), display_version)
print("</div>\n\n<div class="wp-badge">")
printf(__("Version %s"), display_version)
print("</div>\n\n<h2 class="nav-tab-wrapper">\n	<a href="about.php" class="nav-tab nav-tab-active">\n		")
_e("What&#8217;s New")
print("	</a><a href="credits.php" class="nav-tab">\n		")
_e("Credits")
print("	</a><a href="freedoms.php" class="nav-tab">\n		")
_e("Freedoms")
print("	</a>\n</h2>\n\n<div class="changelog point-releases">\n	<h3>")
print(_n("Maintenance and Security Release", "Maintenance and Security Releases", 1))
print("</h3>\n	<p>")
printf(_n("<strong>Version %1$s</strong> addressed some security issues and fixed %2$s bug.", "<strong>Version %1$s</strong> addressed some security issues and fixed %2$s bugs.", 37), "3.5.1", number_format_i18n(37))
print("		")
printf(__("For more information, see <a href="%s">the release notes</a>."), "http://codex.wordpress.org/Version_3.5.1")
print(" 	</p>\n</div>\n\n<div class="changelog">\n	<h3>")
_e("New Media Manager")
print("</h3>\n\n	<div class="feature-section col two-col">\n		<img alt="" src="")
print(esc_url(admin_url("images/screenshots/about-media.png")))
print("" class="image-100" />\n\n		<div>\n			<h4>")
_e("Beautiful Interface")
print("</h4>\n			<p>")
_e("Adding media has been streamlined with an all-new experience, making it a breeze to upload files and place them into your posts.")
print("</p>\n		</div>\n		<div class="last-feature">\n			<h4>")
_e("Picturesque Galleries")
print("</h4>\n			<p>")
_e("Creating image galleries is faster with drag and drop reordering, inline caption editing, and simplified controls for layout.")
print("</p>\n		</div>\n	</div>\n</div>\n\n<div class="changelog">\n	<h3>")
_e("New Default Theme")
print("</h3>\n\n	<div class="feature-section images-stagger-right">\n		<img alt="" src="")
print(esc_url(admin_url("images/screenshots/about-twenty-twelve.png")))
print("" class="image-66" />\n		<h4>")
_e("Introducing Twenty Twelve")
print("</h4>\n		<p>")
_e("The newest default theme for WordPress is simple, flexible, and elegant.")
print("</p>\n		<p>")
_e("What makes it really shine are the design details, like the gorgeous Open Sans typeface and a fully responsive design that looks great on any device.")
print("</p>\n		<p>")
_e("Naturally, Twenty Twelve supports all the theme features you’ve come to know and love, but it is also designed to be as great for a website as it is for a blog.")
print("</p>\n	</div>\n</div>\n\n<div class="changelog">\n	<h3>")
_e("Retina Ready")
print("</h3>\n\n	<div class="feature-section images-stagger-right">\n		<img alt="" src="")
print(esc_url(admin_url("images/screenshots/about-retina.png")))
print("" class="image-66" />\n		<h4>")
_e("So Sharp You Can&#8217;t See the Pixels")
print("</h4>\n		<p>")
_e("The WordPress dashboard now looks beautiful on high-resolution screens like those found on the iPad, Kindle Fire HD, Nexus 10, and MacBook Pro with Retina Display. Icons and other visual elements are crystal clear and full of detail.")
print("</p>\n	</div>\n</div>\n\n<div class="changelog">\n	<h3>")
_e("Smoother Experience")
print("</h3>\n\n	<div class="feature-section images-stagger-right">\n		<img alt="" src="")
print(esc_url(admin_url("images/screenshots/about-color-picker.png")))
print("" class="image-30" />\n		<h4>")
_e("Better Accessibility")
print("</h4>\n		<p>")
_e("WordPress supports more usage modes than ever before. Screenreaders, touch devices, and mouseless workflows all have improved ease of use and accessibility.")
print("</p>\n\n		<h4>")
_e("More Polish")
print("</h4>\n		<p>")
_e("A number of screens and controls have been refined. For example, a new color picker makes it easier for you to choose that perfect shade of blue.")
print("</p>\n	</div>\n</div>\n\n<div class="changelog">\n	<h3>")
_e("Under the Hood")
print("</h3>\n\n	<div class="feature-section col three-col">\n		<div>\n			<h4>")
_e("Meta Query Additions")
print("</h4>\n			<p>")
_e("The <code>WP_Comment_Query</code> and <code>WP_User_Query</code> classes now support meta queries just like <code>WP_Query.</code> Meta queries now support querying for objects without a particular meta key.")
print("</p>\n		</div>\n		<div>\n			<h4>")
_e("Post Objects")
print("</h4>\n			<p>")
_e("Post objects are now instances of a <code>WP_Post</code> class, which improves performance by loading selected properties on demand.")
print("</p>\n		</div>\n		<div class="last-feature">\n			<h4>")
_e("Image Editing API")
print("</h4>\n			<p>")
_e("The <code>WP_Image_Editor</code> class abstracts image editing functionality such as cropping and scaling, and uses ImageMagick when available.")
print("</p>\n		</div>\n	</div>\n\n	<div class="feature-section col three-col">\n		<div>\n			<h4>")
_e("Multisite Improvements")
print("</h4>\n			<p>")
_e("<code>switch_to_blog()</code> is now significantly faster and more reliable.")
print("</p>\n		</div>\n		<div>\n			<h4>")
_e("XML-RPC API")
print("</h4>\n			<p>")
printf(__("The <a href="%s">WordPress API</a> is now always enabled, and supports fetching users, editing profiles, managing post revisions, and searching posts."), __("http://codex.wordpress.org/XML-RPC_WordPress_API"))
print("</p>\n		</div>\n		<div class="last-feature">\n			<h4>")
_e("External Libraries")
print("</h4>\n			<p>")
printf(__("WordPress now includes the <a href="%1$s">Underscore</a> and <a href="%2$s">Backbone</a> JavaScript libraries. TinyMCE, jQuery, jQuery UI, and SimplePie have all been updated to the latest versions."), "http://underscorejs.org/", "http://backbonejs.org/")
print("</p>\n		</div>\n	</div>\n</div>\n\n<div class="return-to-dashboard">\n	")
if current_user_can("update_core")&&isset(_GET["updated"]):
  print("	<a href="")
  print(esc_url(self_admin_url("update-core.php")))
  print("">")
  _e("Return to Updates") if is_multisite() else _e("Return to Dashboard &rarr; Updates")
  print("</a> |\n	")
print("	<a href="")
print(esc_url(self_admin_url()))
print("">")
_e("Go to Dashboard &rarr; Home") if is_blog_admin() else _e("Go to Dashboard")
print("</a>\n</div>\n\n</div>\n")
include(ABSPATH+"wp-admin/admin-footer.php")
return _n_noop("Maintenance Release", "Maintenance Releases")
_n_noop("Security Release", "Security Releases")
_n_noop("Maintenance and Security Release", "Maintenance and Security Releases")
_n_noop("<strong>Version %1$s</strong> addressed a security issue.", "<strong>Version %1$s</strong> addressed some security issues.")
_n_noop("<strong>Version %1$s</strong> addressed %2$s bug.", "<strong>Version %1$s</strong> addressed %2$s bugs.")
_n_noop("<strong>Version %1$s</strong> addressed a security issue and fixed %2$s bug.", "<strong>Version %1$s</strong> addressed a security issue and fixed %2$s bugs.")
_n_noop("<strong>Version %1$s</strong> addressed some security issues and fixed %2$s bug.", "<strong>Version %1$s</strong> addressed some security issues and fixed %2$s bugs.")
__("For more information, see <a href="%s">the release notes</a>.")
