#!/usr/bin/python
#-*- coding: utf-8 -*-
if !defined("ABSPATH"):
  die("-1")
print("<form name="post" action="comment.php" method="post" id="post">\n")
wp_nonce_field("update-comment_"+comment.comment_ID)
print("<div class="wrap">\n")
screen_icon()
print("<h2>")
_e("Edit Comment")
print("</h2>\n\n<div id="poststuff">\n<input type="hidden" name="user_ID" value="")
print(user_ID)
print("" />\n<input type="hidden" name="action" value="editedcomment" />\n<input type="hidden" name="comment_ID" value="")
print(esc_attr(comment.comment_ID))
print("" />\n<input type="hidden" name="comment_post_ID" value="")
print(esc_attr(comment.comment_post_ID))
print("" />\n\n<div id="post-body" class="metabox-holder columns-2">\n<div id="post-body-content">\n<div id="namediv" class="stuffbox">\n<h3><label for="name">")
_e("Author")
print("</label></h3>\n<div class="inside">\n<table class="form-table editcomment">\n<tbody>\n<tr valign="top">\n	<td class="first">")
_e("Name:")
print("</td>\n	<td><input type="text" name="newcomment_author" size="30" value="")
print(esc_attr(comment.comment_author))
print("" id="name" /></td>\n</tr>\n<tr valign="top">\n	<td class="first">\n	")
if comment.comment_author_email:
  printf(__("E-mail (%s):"), get_comment_author_email_link(__("send e-mail"), "", ""))
else:
  _e("E-mail:")
print("</td>\n	<td><input type="text" name="newcomment_author_email" size="30" value="")
print(comment.comment_author_email)
print("" id="email" /></td>\n</tr>\n<tr valign="top">\n	<td class="first">\n	")
if !empty(comment.comment_author_url)&&"http://"!=comment.comment_author_url:
  link = "<a href=""+comment.comment_author_url+"" rel="external nofollow" target="_blank">"+__("visit site")+"</a>"
  printf(__("URL (%s):"), apply_filters("get_comment_author_link", link))
else:
  _e("URL:")
print("</td>\n	<td><input type="text" id="newcomment_author_url" name="newcomment_author_url" size="30" class="code" value="")
print(esc_attr(comment.comment_author_url))
print("" /></td>\n</tr>\n</tbody>\n</table>\n<br />\n</div>\n</div>\n\n<div id="postdiv" class="postarea">\n")
quicktags_settings = {"buttons":"strong,em,link,block,del,ins,img,ul,ol,li,code,spell,close"}
wp_editor(comment.comment_content, "content", {"media_buttons":False, "tinymce":False, "quicktags":quicktags_settings})
wp_nonce_field("closedpostboxes", "closedpostboxesnonce", False)
print("</div>\n</div><!-- /post-body-content -->\n\n<div id="postbox-container-1" class="postbox-container">\n<div id="submitdiv" class="stuffbox" >\n<h3><span class='hndle'>")
_e("Status")
print("</span></h3>\n<div class="inside">\n<div class="submitbox" id="submitcomment">\n<div id="minor-publishing">\n\n<div id="minor-publishing-actions">\n<div id="preview-action">\n<a class="preview button" href="")
print(get_comment_link())
print("" target="_blank">")
_e("View Comment")
print("</a>\n</div>\n<div class="clear"></div>\n</div>\n\n<div id="misc-publishing-actions">\n\n<div class="misc-pub-section" id="comment-status-radio">\n<label class="approved"><input type="radio"")
checked(comment.comment_approved, "1")
print(" name="comment_status" value="1" />")
_ex("Approved", "adjective")
print("</label><br />\n<label class="waiting"><input type="radio"")
checked(comment.comment_approved, "0")
print(" name="comment_status" value="0" />")
_ex("Pending", "adjective")
print("</label><br />\n<label class="spam"><input type="radio"")
checked(comment.comment_approved, "spam")
print(" name="comment_status" value="spam" />")
_ex("Spam", "adjective")
print("</label>\n</div>\n\n<div class="misc-pub-section curtime">\n")
datef = __("M j, Y @ G:i")
stamp = __("Submitted on: <b>%1$s</b>")
date = date_i18n(datef, strtotime(comment.comment_date))
print("<span id="timestamp">")
printf(stamp, date)
print("</span>&nbsp;<a href="#edit_timestamp" class="edit-timestamp hide-if-no-js">")
_e("Edit")
print("</a>\n<div id='timestampdiv' class='hide-if-js'>")
touch_time("editcomment"==action, 0)
print("</div>\n</div>\n</div> <!-- misc actions -->\n<div class="clear"></div>\n</div>\n\n<div id="major-publishing-actions">\n<div id="delete-action">\n")
print("<a class='submitdelete deletion' href='"+wp_nonce_url("comment.php?action="+"deletecomment" if !EMPTY_TRASH_DAYS else "trashcomment"+"&amp;c="+comment.comment_ID+"&amp;_wp_original_http_referer="+urlencode(wp_get_referer()), "delete-comment_"+comment.comment_ID)+"'>"+__("Delete Permanently") if !EMPTY_TRASH_DAYS else __("Move to Trash")+"</a>\n")
print("</div>\n<div id="publishing-action">\n")
submit_button(__("Update"), "primary", "save", False)
print("</div>\n<div class="clear"></div>\n</div>\n</div>\n</div>\n</div><!-- /submitdiv -->\n</div>\n\n<div id="postbox-container-2" class="postbox-container">\n")
do_action("add_meta_boxes", "comment", comment)
do_action("add_meta_boxes_comment", comment)
do_meta_boxes(, "normal", comment)
print("</div>\n\n<input type="hidden" name="c" value="")
print(esc_attr(comment.comment_ID))
print("" />\n<input type="hidden" name="p" value="")
print(esc_attr(comment.comment_post_ID))
print("" />\n<input name="referredby" type="hidden" id="referredby" value="")
print(esc_url(stripslashes(wp_get_referer())))
print("" />\n")
wp_original_referer_field(True, "previous")
print("<input type="hidden" name="noredir" value="1" />\n\n</div><!-- /post-body -->\n</div>\n</div>\n</form>\n\n<script type="text/javascript">\ntry{document.post.name.focus();}catch(e){}\n</script>\n")
