#!/usr/bin/python
#-*- coding: utf-8 -*-
if !defined("ABSPATH"):
  die("-1")
if !empty(link_id):
  heading = sprintf(__("<a href="%s">Links</a> / Edit Link"), "link-manager.php")
  submit_text = __("Update Link")
  form = "<form name="editlink" id="editlink" method="post" action="link.php">"
  nonce_action = "update-bookmark_"+link_id
else:
  heading = sprintf(__("<a href="%s">Links</a> / Add New Link"), "link-manager.php")
  submit_text = __("Add Link")
  form = "<form name="addlink" id="addlink" method="post" action="link.php">"
  nonce_action = "add-bookmark"
require_once("./includes/meta-boxes.php")
add_meta_box("linksubmitdiv", __("Save"), "link_submit_meta_box", , "side", "core")
add_meta_box("linkcategorydiv", __("Categories"), "link_categories_meta_box", , "normal", "core")
add_meta_box("linktargetdiv", __("Target"), "link_target_meta_box", , "normal", "core")
add_meta_box("linkxfndiv", __("Link Relationship (XFN)"), "link_xfn_meta_box", , "normal", "core")
add_meta_box("linkadvanceddiv", __("Advanced"), "link_advanced_meta_box", , "normal", "core")
do_action("add_meta_boxes", "link", link)
do_action("add_meta_boxes_link", link)
do_action("do_meta_boxes", "link", "normal", link)
do_action("do_meta_boxes", "link", "advanced", link)
do_action("do_meta_boxes", "link", "side", link)
add_screen_option("layout_columns", {"max":2, "default":2})
get_current_screen()
get_current_screen()
require_once("admin-header.php")
print("\n<div class="wrap">\n")
screen_icon()
print("<h2>")
print(esc_html(title))
print("  <a href="link-add.php" class="add-new-h2">")
print(esc_html_x("Add New", "link"))
print("</a></h2>\n\n")
if isset(_GET["added"]):
  print("<div id="message" class="updated"><p>")
  _e("Link added.")
  print("</p></div>\n")
print("\n")
if !empty(form):
  print(form)
if !empty(link_added):
  print(link_added)
wp_nonce_field(nonce_action)
wp_nonce_field("closedpostboxes", "closedpostboxesnonce", False)
wp_nonce_field("meta-box-order", "meta-box-order-nonce", False)
print("\n<div id="poststuff">\n\n<div id="post-body" class="metabox-holder columns-")
print("1" if 1==get_current_screen() else "2")
print("">\n<div id="post-body-content">\n<div id="namediv" class="stuffbox">\n<h3><label for="link_name">")
_ex("Name", "link name")
print("</label></h3>\n<div class="inside">\n	<input type="text" name="link_name" size="30" value="")
print(esc_attr(link.link_name))
print("" id="link_name" />\n    <p>")
_e("Example: Nifty blogging software")
print("</p>\n</div>\n</div>\n\n<div id="addressdiv" class="stuffbox">\n<h3><label for="link_url">")
_e("Web Address")
print("</label></h3>\n<div class="inside">\n	<input type="text" name="link_url" size="30" class="code" value="")
print(esc_attr(link.link_url))
print("" id="link_url" />\n    <p>")
_e("Example: <code>http://wordpress.org/</code> &#8212; don&#8217;t forget the <code>http://</code>")
print("</p>\n</div>\n</div>\n\n<div id="descriptiondiv" class="stuffbox">\n<h3><label for="link_description">")
_e("Description")
print("</label></h3>\n<div class="inside">\n	<input type="text" name="link_description" size="30" value="")
print(esc_attr(link.link_description) if isset(link.link_description) else "")
print("" id="link_description" />\n    <p>")
_e("This will be shown when someone hovers over the link in the blogroll, or optionally below the link.")
print("</p>\n</div>\n</div>\n</div><!-- /post-body-content -->\n\n<div id="postbox-container-1" class="postbox-container">\n")
do_action("submitlink_box")
side_meta_boxes = do_meta_boxes("link", "side", link)
print("</div>\n<div id="postbox-container-2" class="postbox-container">\n")
do_meta_boxes(, "normal", link)
do_meta_boxes(, "advanced", link)
print("</div>\n")
if link_id:
  print("<input type="hidden" name="action" value="save" />\n<input type="hidden" name="link_id" value="")
  print(link_id)
  print("" />\n<input type="hidden" name="order_by" value="")
  print(esc_attr(order_by))
  print("" />\n<input type="hidden" name="cat_id" value="")
  print(cat_id)
  print("" />\n")
else:
  print("<input type="hidden" name="action" value="add" />\n")
print("\n</div>\n</div>\n\n</form>\n</div>\n")
