#!/usr/bin/python
#-*- coding: utf-8 -*-
require_once("./admin.php")
title = __("Freedoms")
display_versionexplode("-", wp_version)
include(ABSPATH+"wp-admin/admin-header.php")
print("<div class="wrap about-wrap">\n\n<h1>")
printf(__("Welcome to WordPress %s"), display_version)
print("</h1>\n\n<div class="about-text">")
printf(__("Thank you for updating to the latest version! WordPress %s is more polished and enjoyable than ever before. We hope you like it."), display_version)
print("</div>\n\n<div class="wp-badge">")
printf(__("Version %s"), display_version)
print("</div>\n\n<h2 class="nav-tab-wrapper">\n	<a href="about.php" class="nav-tab">\n		")
_e("What&#8217;s New")
print("	</a><a href="credits.php" class="nav-tab">\n		")
_e("Credits")
print("	</a><a href="freedoms.php" class="nav-tab nav-tab-active">\n		")
_e("Freedoms")
print("	</a>\n</h2>\n\n<p class="about-description">")
printf(__("WordPress is Free and open source software, built by a distributed community of mostly volunteer developers from around the world. WordPress comes with some awesome, worldview-changing rights courtesy of its <a href="%s">license</a>, the GPL."), "http://wordpress.org/about/license/")
print("</p>\n\n<ol start="0">\n	<li><p>")
_e("You have the freedom to run the program, for any purpose.")
print("</p></li>\n	<li><p>")
_e("You have access to the source code, the freedom to study how the program works, and the freedom to change it to make it do what you wish.")
print("</p></li>\n	<li><p>")
_e("You have the freedom to redistribute copies of the original program so you can help your neighbor.")
print("</p></li>\n	<li><p>")
_e("You have the freedom to distribute copies of your modified versions to others. By doing this you can give the whole community a chance to benefit from your changes.")
print("</p></li>\n</ol>\n\n<p>")
printf(__("WordPress grows when people like you tell their friends about it, and the thousands of businesses and services that are built on and around WordPress share that fact with their users. We&#8217;re flattered every time someone spreads the good word, just make sure to <a href="%s">check out our trademark guidelines</a> first."), "http://wordpressfoundation.org/trademark-policy/")
print("</p>\n\n<p>")
plugins_url = admin_url("plugins.php") if current_user_can("activate_plugins") else "http://wordpress.org/extend/plugins/"
themes_url = admin_url("themes.php") if current_user_can("switch_themes") else "http://wordpress.org/extend/themes/"
printf(__("Every plugin and theme in WordPress.org&#8217;s directory is 100%% GPL or a similarly free and compatible license, so you can feel safe finding <a href="%1$s">plugins</a> and <a href="%2$s">themes</a> there. If you get a plugin or theme from another source, make sure to <a href="%3$s">ask them if it&#8217;s GPL</a> first. If they don&#8217;t respect the WordPress license, we don&#8217;t recommend them."), plugins_url, themes_url, "http://wordpress.org/about/license/")
print("</p>\n\n<p>")
_e("Don&#8217;t you wish all software came with these freedoms? So do we! For more information, check out the <a href="http://www.fsf.org/">Free Software Foundation</a>.")
print("</p>\n\n</div>\n")
include(ABSPATH+"wp-admin/admin-footer.php")
