#!/usr/bin/python
#-*- coding: utf-8 -*-
require_once("./admin.php")
if !current_user_can("manage_options"):
  wp_die(__("You do not have sufficient permissions to manage options for this site."))
title = __("Writing Settings")
parent_file = "options-general.php"
get_current_screen()
get_current_screen()
if apply_filters("enable_post_by_email_configuration", True):
  get_current_screen()
if apply_filters("enable_update_services_configuration", True):
  get_current_screen()
get_current_screen()
include("./admin-header.php")
print("\n<div class="wrap">\n")
screen_icon()
print("<h2>")
print(esc_html(title))
print("</h2>\n\n<form method="post" action="options.php">\n")
settings_fields("writing")
print("\n<table class="form-table">\n<tr valign="top">\n<th scope="row">")
_e("Formatting")
print("</th>\n<td><fieldset><legend class="screen-reader-text"><span>")
_e("Formatting")
print("</span></legend>\n<label for="use_smilies">\n<input name="use_smilies" type="checkbox" id="use_smilies" value="1" ")
checked("1", get_option("use_smilies"))
print(" />\n")
_e("Convert emoticons like <code>:-)</code> and <code>:-P</code> to graphics on display")
print("</label><br />\n<label for="use_balanceTags"><input name="use_balanceTags" type="checkbox" id="use_balanceTags" value="1" ")
checked("1", get_option("use_balanceTags"))
print(" /> ")
_e("WordPress should correct invalidly nested XHTML automatically")
print("</label>\n</fieldset></td>\n</tr>\n<tr valign="top">\n<th scope="row"><label for="default_category">")
_e("Default Post Category")
print("</label></th>\n<td>\n")
wp_dropdown_categories({"hide_empty":0, "name":"default_category", "orderby":"name", "selected":get_option("default_category"), "hierarchical":True})
print("</td>\n</tr>\n")
if current_theme_supports("post-formats"):
  post_formats = get_theme_support("post-formats")
  if is_array(post_formats[0]):
    print("<tr valign="top">\n<th scope="row"><label for="default_post_format">")
    _e("Default Post Format")
    print("</label></th>\n<td>\n	<select name="default_post_format" id="default_post_format">\n		<option value="0">")
    _e("Standard")
    print("</option>\n")
    for format in post_formats[0]:
      print("		<option")
      selected(get_option("default_post_format"), format)
      print(" value="")
      print(esc_attr(format))
      print("">")
      print(esc_html(get_post_format_string(format)))
      print("</option>\n")
    print("	</select>\n</td>\n</tr>\n")
if get_option("link_manager_enabled"):
  print("<tr valign="top">\n<th scope="row"><label for="default_link_category">")
  _e("Default Link Category")
  print("</label></th>\n<td>\n")
  wp_dropdown_categories({"hide_empty":0, "name":"default_link_category", "orderby":"name", "selected":get_option("default_link_category"), "hierarchical":True, "taxonomy":"link_category"})
  print("</td>\n</tr>\n")
print("\n")
do_settings_fields("writing", "default")
do_settings_fields("writing", "remote_publishing")
print("</table>\n\n<h3 class="title">")
_e("Press This")
print("</h3>\n<p>")
_e("Press This is a bookmarklet: a little app that runs in your browser and lets you grab bits of the web.")
print("</p>\n<p>")
_e("Use Press This to clip text, images and videos from any web page. Then edit and add more straight from Press This before you save or publish it in a post on your site.")
print("</p>\n<p>")
_e("Drag-and-drop the following link to your bookmarks bar or right click it and add it to your favorites for a posting shortcut.")
print("</p>\n<p class="pressthis"><a onclick="return false;" oncontextmenu="if(window.navigator.userAgent.indexOf('WebKit')!=-1||window.navigator.userAgent.indexOf('MSIE')!=-1)jQuery('.pressthis-code').show().find('textarea').focus().select();return false;" href="")
print(htmlspecialchars(get_shortcut_link()))
print(""><span>")
_e("Press This")
print("</span></a></p>\n<div class="pressthis-code" style="display:none;">\n	<p class="description">")
_e("If your bookmarks toolbar is hidden: copy the code below, open your Bookmarks manager, create new bookmark, type Press This into the name field and paste the code into the URL field.")
print("</p>\n	<p><textarea rows="5" cols="120" readonly="readonly">")
print(htmlspecialchars(get_shortcut_link()))
print("</textarea></p>\n</div>\n\n")
if apply_filters("enable_post_by_email_configuration", True):
  print("<h3>")
  _e("Post via e-mail")
  print("</h3>\n<p>")
  printf(__("To post to WordPress by e-mail you must set up a secret e-mail account with POP3 access. Any mail received at this address will be posted, so it&#8217;s a good idea to keep this address very secret. Here are three random strings you could use: <kbd>%s</kbd>, <kbd>%s</kbd>, <kbd>%s</kbd>."), wp_generate_password(8, False), wp_generate_password(8, False), wp_generate_password(8, False))
  print("</p>\n\n<table class="form-table">\n<tr valign="top">\n<th scope="row"><label for="mailserver_url">")
  _e("Mail Server")
  print("</label></th>\n<td><input name="mailserver_url" type="text" id="mailserver_url" value="")
  form_option("mailserver_url")
  print("" class="regular-text code" />\n<label for="mailserver_port">")
  _e("Port")
  print("</label>\n<input name="mailserver_port" type="text" id="mailserver_port" value="")
  form_option("mailserver_port")
  print("" class="small-text" />\n</td>\n</tr>\n<tr valign="top">\n<th scope="row"><label for="mailserver_login">")
  _e("Login Name")
  print("</label></th>\n<td><input name="mailserver_login" type="text" id="mailserver_login" value="")
  form_option("mailserver_login")
  print("" class="regular-text ltr" /></td>\n</tr>\n<tr valign="top">\n<th scope="row"><label for="mailserver_pass">")
  _e("Password")
  print("</label></th>\n<td>\n<input name="mailserver_pass" type="text" id="mailserver_pass" value="")
  form_option("mailserver_pass")
  print("" class="regular-text ltr" />\n</td>\n</tr>\n<tr valign="top">\n<th scope="row"><label for="default_email_category">")
  _e("Default Mail Category")
  print("</label></th>\n<td>\n")
  wp_dropdown_categories({"hide_empty":0, "name":"default_email_category", "orderby":"name", "selected":get_option("default_email_category"), "hierarchical":True})
  print("</td>\n</tr>\n")
  do_settings_fields("writing", "post_via_email")
  print("</table>\n")
print("\n")
if apply_filters("enable_update_services_configuration", True):
  print("<h3>")
  _e("Update Services")
  print("</h3>\n\n")
  if 1==get_option("blog_public"):
    print("\n<p><label for="ping_sites">")
    _e("When you publish a new post, WordPress automatically notifies the following site update services. For more about this, see <a href="http://codex.wordpress.org/Update_Services">Update Services</a> on the Codex. Separate multiple service <abbr title="Universal Resource Locator">URL</abbr>s with line breaks.")
    print("</label></p>\n\n<textarea name="ping_sites" id="ping_sites" class="large-text code" rows="3">")
    print(esc_textarea(get_option("ping_sites")))
    print("</textarea>\n\n")
  else:
    print("\n	<p>")
    printf(__("WordPress is not notifying any <a href="http://codex.wordpress.org/Update_Services">Update Services</a> because of your site&#8217;s <a href="%s">visibility settings</a>."), "options-reading.php")
    print("</p>\n\n")
print("\n\n")
do_settings_sections("writing")
print("\n")
submit_button()
print("</form>\n</div>\n\n")
include("./admin-footer.php")
