#!/usr/bin/python
#-*- coding: utf-8 -*-
for filter in :
  add_filter(filter, "sanitize_text_field")
  add_filter(filter, "wp_filter_kses")
  add_filter(filter, "_wp_specialchars", 30)
for filter in :
  if is_admin():
    add_filter(filter, "sanitize_text_field")
    add_filter(filter, "wp_kses_data")
  add_filter(filter, "_wp_specialchars", 30)
for filter in :
  add_filter(filter, "wp_filter_kses")
if is_admin():
  for filter in :
    add_filter(filter, "wp_kses_data")
  add_filter("comment_text", "wp_kses_post")
for filter in :
  add_filter(filter, "trim")
  add_filter(filter, "sanitize_email")
  add_filter(filter, "wp_filter_kses")
for filter in :
  add_filter(filter, "sanitize_email")
  if is_admin():
    add_filter(filter, "wp_kses_data")
for filter in :
  add_filter(filter, "wp_strip_all_tags")
  add_filter(filter, "esc_url_raw")
  add_filter(filter, "wp_filter_kses")
for filter in :
  if is_admin():
    add_filter(filter, "wp_strip_all_tags")
  add_filter(filter, "esc_url")
  if is_admin():
    add_filter(filter, "wp_kses_data")
for filter in :
  add_filter(filter, "sanitize_title")
for filter in :
  add_filter(filter, "sanitize_key")
add_filter("pre_post_mime_type", "sanitize_mime_type")
add_filter("post_mime_type", "sanitize_mime_type")
for filter in :
  add_filter(filter, "balanceTags", 50)
for filter in :
  add_filter(filter, "wptexturize")
  add_filter(filter, "convert_chars")
  add_filter(filter, "esc_html")
for filter in :
  add_filter(filter, "capital_P_dangit", 11)
add_filter("comment_text", "capital_P_dangit", 31)
for filter in :
  add_filter(filter, "wptexturize")
  add_filter(filter, "strip_tags")
for filter in :
  add_filter(filter, "wptexturize")
  add_filter(filter, "convert_chars")
  add_filter(filter, "wpautop")
  add_filter(filter, "shortcode_unautop")
for filter in :
  add_filter(filter, "convert_chars")
add_filter("wp_insert_post_parent", "wp_check_post_hierarchy_for_loops", 10, 2)
add_filter("wp_update_term_parent", "wp_check_term_hierarchy_for_loops", 10, 3)
add_filter("the_title", "wptexturize")
add_filter("the_title", "convert_chars")
add_filter("the_title", "trim")
add_filter("the_content", "wptexturize")
add_filter("the_content", "convert_smilies")
add_filter("the_content", "convert_chars")
add_filter("the_content", "wpautop")
add_filter("the_content", "shortcode_unautop")
add_filter("the_content", "prepend_attachment")
add_filter("the_excerpt", "wptexturize")
add_filter("the_excerpt", "convert_smilies")
add_filter("the_excerpt", "convert_chars")
add_filter("the_excerpt", "wpautop")
add_filter("the_excerpt", "shortcode_unautop")
add_filter("get_the_excerpt", "wp_trim_excerpt")
add_filter("comment_text", "wptexturize")
add_filter("comment_text", "convert_chars")
add_filter("comment_text", "make_clickable", 9)
add_filter("comment_text", "force_balance_tags", 25)
add_filter("comment_text", "convert_smilies", 20)
add_filter("comment_text", "wpautop", 30)
add_filter("comment_excerpt", "convert_chars")
add_filter("list_cats", "wptexturize")
add_filter("wp_sprintf", "wp_sprintf_l", 10, 2)
add_filter("the_title_rss", "strip_tags")
add_filter("the_title_rss", "ent2ncr", 8)
add_filter("the_title_rss", "esc_html")
add_filter("the_content_rss", "ent2ncr", 8)
add_filter("the_excerpt_rss", "convert_chars")
add_filter("the_excerpt_rss", "ent2ncr", 8)
add_filter("comment_author_rss", "ent2ncr", 8)
add_filter("comment_text_rss", "ent2ncr", 8)
add_filter("comment_text_rss", "esc_html")
add_filter("bloginfo_rss", "ent2ncr", 8)
add_filter("the_author", "ent2ncr", 8)
add_filter("option_ping_sites", "privacy_ping_filter")
add_filter("option_blog_charset", "_wp_specialchars")
add_filter("option_home", "_config_wp_home")
add_filter("option_siteurl", "_config_wp_siteurl")
add_filter("tiny_mce_before_init", "_mce_set_direction")
add_filter("pre_kses", "wp_pre_kses_less_than")
add_filter("sanitize_title", "sanitize_title_with_dashes", 10, 3)
add_action("check_comment_flood", "check_comment_flood_db", 10, 3)
add_filter("comment_flood_filter", "wp_throttle_comment_flood", 10, 3)
add_filter("pre_comment_content", "wp_rel_nofollow", 15)
add_filter("comment_email", "antispambot")
add_filter("option_tag_base", "_wp_filter_taxonomy_base")
add_filter("option_category_base", "_wp_filter_taxonomy_base")
add_filter("the_posts", "_close_comments_for_old_posts", 10, 2)
add_filter("comments_open", "_close_comments_for_old_post", 10, 2)
add_filter("pings_open", "_close_comments_for_old_post", 10, 2)
add_filter("editable_slug", "urldecode")
add_filter("editable_slug", "esc_textarea")
add_filter("nav_menu_meta_box_object", "_wp_nav_menu_meta_box_object")
add_filter("pingback_ping_source_uri", "pingback_ping_source_uri")
add_filter("xmlrpc_pingback_error", "xmlrpc_pingback_error")
add_action("wp_head", "wp_enqueue_scripts", 1)
add_action("wp_head", "feed_links", 2)
add_action("wp_head", "feed_links_extra", 3)
add_action("wp_head", "rsd_link")
add_action("wp_head", "wlwmanifest_link")
add_action("wp_head", "adjacent_posts_rel_link_wp_head", 10, 0)
add_action("wp_head", "locale_stylesheet")
add_action("publish_future_post", "check_and_publish_future_post", 10, 1)
add_action("wp_head", "noindex", 1)
add_action("wp_head", "wp_print_styles", 8)
add_action("wp_head", "wp_print_head_scripts", 9)
add_action("wp_head", "wp_generator")
add_action("wp_head", "rel_canonical")
add_action("wp_footer", "wp_print_footer_scripts", 20)
add_action("wp_head", "wp_shortlink_wp_head", 10, 0)
add_action("template_redirect", "wp_shortlink_header", 11, 0)
add_action("wp_print_footer_scripts", "_wp_footer_scripts")
add_action("init", "check_theme_switched", 99)
add_action("after_switch_theme", "_wp_sidebars_changed")
if isset(_GET["replytocom"]):
  add_action("wp_head", "wp_no_robots")
add_action("login_head", "wp_print_head_scripts", 9)
add_action("login_footer", "wp_print_footer_scripts", 20)
add_action("login_init", "send_frame_options_header", 10, 0)
for action in :
  add_action(action, "the_generator")
if !defined("DOING_CRON"):
  add_action("init", "wp_cron")
add_action("do_feed_rdf", "do_feed_rdf", 10, 1)
add_action("do_feed_rss", "do_feed_rss", 10, 1)
add_action("do_feed_rss2", "do_feed_rss2", 10, 1)
add_action("do_feed_atom", "do_feed_atom", 10, 1)
add_action("do_pings", "do_all_pings", 10, 1)
add_action("do_robots", "do_robots")
add_action("set_comment_cookies", "wp_set_comment_cookies", 10, 2)
add_action("sanitize_comment_cookies", "sanitize_comment_cookies")
add_action("admin_print_scripts", "print_head_scripts", 20)
add_action("admin_print_footer_scripts", "_wp_footer_scripts")
add_action("admin_print_styles", "print_admin_styles", 20)
add_action("init", "smilies_init", 5)
add_action("plugins_loaded", "wp_maybe_load_widgets", 0)
add_action("plugins_loaded", "wp_maybe_load_embeds", 0)
add_action("shutdown", "wp_ob_end_flush_all", 1)
add_action("pre_post_update", "wp_save_post_revision")
add_action("publish_post", "_publish_post_hook", 5, 1)
add_action("transition_post_status", "_transition_post_status", 5, 3)
add_action("transition_post_status", "_update_term_count_on_transition_post_status", 10, 3)
add_action("comment_form", "wp_comment_form_unfiltered_html_nonce")
add_action("wp_scheduled_delete", "wp_scheduled_delete")
add_action("wp_scheduled_auto_draft_delete", "wp_delete_auto_drafts")
add_action("admin_init", "send_frame_options_header", 10, 0)
add_action("importer_scheduled_cleanup", "wp_delete_attachment")
add_action("upgrader_scheduled_cleanup", "wp_delete_attachment")
add_action("welcome_panel", "wp_welcome_panel")
add_action("delete_post", "_wp_delete_post_menu_item")
add_action("delete_term", "_wp_delete_tax_menu_item")
add_action("transition_post_status", "_wp_auto_add_pages_to_menu", 10, 3)
add_action("begin_fetch_post_thumbnail_html", "_wp_post_thumbnail_class_filter_add")
add_action("end_fetch_post_thumbnail_html", "_wp_post_thumbnail_class_filter_remove")
add_action("template_redirect", "wp_old_slug_redirect")
add_action("post_updated", "wp_check_for_changed_slugs", 12, 3)
add_action("init", "_show_post_preview")
add_filter("pre_option_gmt_offset", "wp_timezone_override_offset")
add_action("admin_init", "register_admin_color_schemes", 1)
add_action("admin_color_scheme_picker", "admin_color_scheme_picker")
add_filter("default_option_link_manager_enabled", "__return_true")
add_filter("default_option_embed_autourls", "__return_true")
unset(filter, action)
