#!/usr/bin/python
#-*- coding: utf-8 -*-
header("Content-Type: "+feed_content_type("rss-http")+"; charset="+get_option("blog_charset"), True)
more = 1
print("<?xml version="1.0" encoding=""+get_option("blog_charset")+""?"+">")
print("<rss version="0.92">\n<channel>\n	<title>")
bloginfo_rss("name")
wp_title_rss()
print("</title>\n	<link>")
bloginfo_rss("url")
print("</link>\n	<description>")
bloginfo_rss("description")
print("</description>\n	<lastBuildDate>")
print(mysql2date("D, d M Y H:i:s +0000", get_lastpostmodified("GMT"), False))
print("</lastBuildDate>\n	<docs>http://backend.userland.com/rss092</docs>\n	<language>")
bloginfo_rss("language")
print("</language>\n	")
do_action("rss_head")
print("\n")
while :
  the_post()
  print("	<item>\n		<title>")
  the_title_rss()
  print("</title>\n		<description><![CDATA[")
  the_excerpt_rss()
  print("]]></description>\n		<link>")
  the_permalink_rss()
  print("</link>\n		")
  do_action("rss_item")
  print("	</item>\n")
print("</channel>\n</rss>\n")
