#!/usr/bin/python
#-*- coding: utf-8 -*-
header("Content-Type: "+feed_content_type("rdf")+"; charset="+get_option("blog_charset"), True)
more = 1
print("<?xml version="1.0" encoding=""+get_option("blog_charset")+""?"+">")
print("<rdf:RDF\n	xmlns="http://purl.org/rss/1.0/"\n	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"\n	xmlns:dc="http://purl.org/dc/elements/1.1/"\n	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"\n	xmlns:admin="http://webns.net/mvcb/"\n	xmlns:content="http://purl.org/rss/1.0/modules/content/"\n	")
do_action("rdf_ns")
print(">\n<channel rdf:about="")
bloginfo_rss("url")
print("">\n	<title>")
bloginfo_rss("name")
wp_title_rss()
print("</title>\n	<link>")
bloginfo_rss("url")
print("</link>\n	<description>")
bloginfo_rss("description")
print("</description>\n	<dc:date>")
print(mysql2date("Y-m-d\TH:i:s\Z", get_lastpostmodified("GMT"), False))
print("</dc:date>\n	<sy:updatePeriod>")
print(apply_filters("rss_update_period", "hourly"))
print("</sy:updatePeriod>\n	<sy:updateFrequency>")
print(apply_filters("rss_update_frequency", "1"))
print("</sy:updateFrequency>\n	<sy:updateBase>2000-01-01T12:00+00:00</sy:updateBase>\n	")
do_action("rdf_header")
print("	<items>\n		<rdf:Seq>\n		")
while :
  the_post()
  print("			<rdf:li rdf:resource="")
  the_permalink_rss()
  print(""/>\n		")
print("		</rdf:Seq>\n	</items>\n</channel>\n")
rewind_posts()
while :
  the_post()
  print("<item rdf:about="")
  the_permalink_rss()
  print("">\n	<title>")
  the_title_rss()
  print("</title>\n	<link>")
  the_permalink_rss()
  print("</link>\n	 <dc:date>")
  print(mysql2date("Y-m-d\TH:i:s\Z", post.post_date_gmt, False))
  print("</dc:date>\n	<dc:creator>")
  the_author()
  print("</dc:creator>\n	")
  the_category_rss("rdf")
  if get_option("rss_use_excerpt"):
    print("	<description>")
    the_excerpt_rss()
    print("</description>\n")
  else:
    print("	<description>")
    the_excerpt_rss()
    print("</description>\n	<content:encoded><![CDATA[")
    the_content_feed("rdf")
    print("]]></content:encoded>\n")
  print("	")
  do_action("rdf_item")
  print("</item>\n")
print("</rdf:RDF>\n")
