#!/usr/bin/python
#-*- coding: utf-8 -*-
require_once("./admin.php")
if !current_user_can("manage_options"):
  wp_die(__("You do not have sufficient permissions to manage options for this site."))
title = __("Media Settings")
parent_file = "options-general.php"
media_options_help = "<p>"+__("You can set maximum sizes for images inserted into your written content; you can also insert an image as Full Size.")+"</p>"
if !is_multisite()&&get_option("upload_url_path")||get_option("upload_path")!="wp-content/uploads"&&get_option("upload_path"):
  media_options_help+="<p>"+__("Uploading Files allows you to choose the folder and path for storing your uploaded files.")+"</p>"
media_options_help+="<p>"+__("You must click the Save Changes button at the bottom of the screen for new settings to take effect.")+"</p>"
get_current_screen()
get_current_screen()
include("./admin-header.php")
print("\n<div class="wrap">\n")
screen_icon()
print("<h2>")
print(esc_html(title))
print("</h2>\n\n<form action="options.php" method="post">\n")
settings_fields("media")
print("\n<h3>")
_e("Image sizes")
print("</h3>\n<p>")
_e("The sizes listed below determine the maximum dimensions in pixels to use when inserting an image into the body of a post.")
print("</p>\n\n<table class="form-table">\n<tr valign="top">\n<th scope="row">")
_e("Thumbnail size")
print("</th>\n<td>\n<label for="thumbnail_size_w">")
_e("Width")
print("</label>\n<input name="thumbnail_size_w" type="number" step="1" min="0" id="thumbnail_size_w" value="")
form_option("thumbnail_size_w")
print("" class="small-text" />\n<label for="thumbnail_size_h">")
_e("Height")
print("</label>\n<input name="thumbnail_size_h" type="number" step="1" min="0" id="thumbnail_size_h" value="")
form_option("thumbnail_size_h")
print("" class="small-text" /><br />\n<input name="thumbnail_crop" type="checkbox" id="thumbnail_crop" value="1" ")
checked("1", get_option("thumbnail_crop"))
print("/>\n<label for="thumbnail_crop">")
_e("Crop thumbnail to exact dimensions (normally thumbnails are proportional)")
print("</label>\n</td>\n</tr>\n\n<tr valign="top">\n<th scope="row">")
_e("Medium size")
print("</th>\n<td><fieldset><legend class="screen-reader-text"><span>")
_e("Medium size")
print("</span></legend>\n<label for="medium_size_w">")
_e("Max Width")
print("</label>\n<input name="medium_size_w" type="number" step="1" min="0" id="medium_size_w" value="")
form_option("medium_size_w")
print("" class="small-text" />\n<label for="medium_size_h">")
_e("Max Height")
print("</label>\n<input name="medium_size_h" type="number" step="1" min="0" id="medium_size_h" value="")
form_option("medium_size_h")
print("" class="small-text" />\n</fieldset></td>\n</tr>\n\n<tr valign="top">\n<th scope="row">")
_e("Large size")
print("</th>\n<td><fieldset><legend class="screen-reader-text"><span>")
_e("Large size")
print("</span></legend>\n<label for="large_size_w">")
_e("Max Width")
print("</label>\n<input name="large_size_w" type="number" step="1" min="0" id="large_size_w" value="")
form_option("large_size_w")
print("" class="small-text" />\n<label for="large_size_h">")
_e("Max Height")
print("</label>\n<input name="large_size_h" type="number" step="1" min="0" id="large_size_h" value="")
form_option("large_size_h")
print("" class="small-text" />\n</fieldset></td>\n</tr>\n\n")
do_settings_fields("media", "default")
print("</table>\n\n")
if isset(GLOBALS["wp_settings"]["media"]["embeds"]):
  print("<h3>")
  _e("Embeds")
  print("</h3>\n<table class="form-table">\n")
  do_settings_fields("media", "embeds")
  print("</table>\n")
print("\n")
if !is_multisite():
  print("<h3>")
  _e("Uploading Files")
  print("</h3>\n<table class="form-table">\n")
  if get_option("upload_url_path")||get_option("upload_path")!="wp-content/uploads"&&get_option("upload_path"):
    print("<tr valign="top">\n<th scope="row"><label for="upload_path">")
    _e("Store uploads in this folder")
    print("</label></th>\n<td><input name="upload_path" type="text" id="upload_path" value="")
    print(esc_attr(get_option("upload_path")))
    print("" class="regular-text code" />\n<p class="description">")
    _e("Default is <code>wp-content/uploads</code>")
    print("</p>\n</td>\n</tr>\n\n<tr valign="top">\n<th scope="row"><label for="upload_url_path">")
    _e("Full URL path to files")
    print("</label></th>\n<td><input name="upload_url_path" type="text" id="upload_url_path" value="")
    print(esc_attr(get_option("upload_url_path")))
    print("" class="regular-text code" />\n<p class="description">")
    _e("Configuring this is optional. By default, it should be blank.")
    print("</p>\n</td>\n</tr>\n")
  print("<tr>\n<th scope="row" colspan="2" class="th-full">\n<label for="uploads_use_yearmonth_folders">\n<input name="uploads_use_yearmonth_folders" type="checkbox" id="uploads_use_yearmonth_folders" value="1"")
  checked("1", get_option("uploads_use_yearmonth_folders"))
  print(" />\n")
  _e("Organize my uploads into month- and year-based folders")
  print("</label>\n</th>\n</tr>\n\n")
  do_settings_fields("media", "uploads")
  print("</table>\n")
print("\n")
do_settings_sections("media")
print("\n")
submit_button()
print("\n</form>\n\n</div>\n\n")
include("./admin-footer.php")
