#!/usr/bin/python
#-*- coding: utf-8 -*-
require_once("./admin.php")
if !is_multisite():
  wp_die(__("Multisite support is not enabled."))
if !current_user_can("manage_network_options"):
  wp_die(__("You do not have permission to access this page."))
title = __("Network Settings")
parent_file = "settings.php"
get_current_screen()
get_current_screen()
if _POST:
  do_action("wpmuadminedit", "")
  check_admin_referer("siteoptions")
  checked_options = {"menu_items":[], "registrationnotification":"no", "upload_space_check_disabled":1, "add_new_users":0}
  for option_unchecked_value in checked_options:
    if !isset(_POST[option_name]):
      _POST[option_name] = option_unchecked_value
  options = ["registrationnotification", "registration", "add_new_users", "menu_items", "upload_space_check_disabled", "blog_upload_space", "upload_filetypes", "site_name", "first_post", "first_page", "first_comment", "first_comment_url", "first_comment_author", "welcome_email", "welcome_user_email", "fileupload_maxk", "global_terms_enabled", "illegal_names", "limited_email_domains", "banned_email_domains", "WPLANG", "admin_email"]
  for option_name in options:
    if !isset(_POST[option_name]):
    value = stripslashes_deep(_POST[option_name])
    update_site_option(option_name, value)
  do_action("update_wpmu_options")
  wp_redirect(add_query_arg("updated", "true", network_admin_url("settings.php")))
  exit(0)
include("../admin-header.php")
if isset(_GET["updated"]):
  print("<div id="message" class="updated"><p>")
  _e("Options saved.")
  print("</p></div>")
print("\n<div class="wrap">\n	")
screen_icon("options-general")
print("	<h2>")
print(esc_html(title))
print("</h2>\n	<form method="post" action="settings.php">\n		")
wp_nonce_field("siteoptions")
print("		<h3>")
_e("Operational Settings")
print("</h3>\n		<table class="form-table">\n			<tr valign="top">\n				<th scope="row"><label for="site_name">")
_e("Network Name")
print("</label></th>\n				<td>\n					<input name="site_name" type="text" id="site_name" class="regular-text" value="")
print(esc_attr(current_site.site_name))
print("" />\n					<br />\n					")
_e("What you would like to call this network.")
print("				</td>\n			</tr>\n\n			<tr valign="top">\n				<th scope="row"><label for="admin_email">")
_e("Network Admin Email")
print("</label></th>\n				<td>\n					<input name="admin_email" type="text" id="admin_email" class="regular-text" value="")
print(esc_attr(get_site_option("admin_email")))
print("" />\n					<br />\n					")
printf(__("Registration and support emails will come from this address. An address such as <code>support@%s</code> is recommended."), current_site.domain)
print("				</td>\n			</tr>\n		</table>\n		<h3>")
_e("Registration Settings")
print("</h3>\n		<table class="form-table">\n			<tr valign="top">\n				<th scope="row">")
_e("Allow new registrations")
print("</th>\n				")
if !get_site_option("registration"):
  update_site_option("registration", "none")
reg = get_site_option("registration")
print("				<td>\n					<label><input name="registration" type="radio" id="registration1" value="none"")
checked(reg, "none")
print(" /> ")
_e("Registration is disabled.")
print("</label><br />\n					<label><input name="registration" type="radio" id="registration2" value="user"")
checked(reg, "user")
print(" /> ")
_e("User accounts may be registered.")
print("</label><br />\n					<label><input name="registration" type="radio" id="registration3" value="blog"")
checked(reg, "blog")
print(" /> ")
_e("Logged in users may register new sites.")
print("</label><br />\n					<label><input name="registration" type="radio" id="registration4" value="all"")
checked(reg, "all")
print(" /> ")
_e("Both sites and user accounts can be registered.")
print("</label><br />\n					")
if is_subdomain_install():
  _e("If registration is disabled, please set <code>NOBLOGREDIRECT</code> in <code>wp-config.php</code> to a URL you will redirect visitors to if they visit a non-existent site.")
print("				</td>\n			</tr>\n\n			<tr valign="top">\n				<th scope="row">")
_e("Registration notification")
print("</th>\n				")
if !get_site_option("registrationnotification"):
  update_site_option("registrationnotification", "yes")
print("				<td>\n					<label><input name="registrationnotification" type="checkbox" id="registrationnotification" value="yes"")
checked(get_site_option("registrationnotification"), "yes")
print(" /> ")
_e("Send the network admin an email notification every time someone registers a site or user account.")
print("</label>\n				</td>\n			</tr>\n\n			<tr valign="top" id="addnewusers">\n				<th scope="row">")
_e("Add New Users")
print("</th>\n				<td>\n					<label><input name="add_new_users" type="checkbox" id="add_new_users" value="1"")
checked(get_site_option("add_new_users"))
print(" /> ")
_e("Allow site administrators to add new users to their site via the "Users &rarr; Add New" page.")
print("</label>\n				</td>\n			</tr>\n\n			<tr valign="top">\n				<th scope="row"><label for="illegal_names">")
_e("Banned Names")
print("</label></th>\n				<td>\n					<input name="illegal_names" type="text" id="illegal_names" class="large-text" value="")
print(esc_attr(implode(" ", get_site_option("illegal_names"))))
print("" size="45" />\n					<br />\n					")
_e("Users are not allowed to register these sites. Separate names by spaces.")
print("				</td>\n			</tr>\n\n			<tr valign="top">\n				<th scope="row"><label for="limited_email_domains">")
_e("Limited Email Registrations")
print("</label></th>\n				<td>\n					")
limited_email_domains = get_site_option("limited_email_domains")
limited_email_domains = str_replace(" ", "\n", limited_email_domains)
print("					<textarea name="limited_email_domains" id="limited_email_domains" cols="45" rows="5">\n")
print(esc_textarea("" if limited_email_domains=="" else implode("\n", limited_email_domains)))
print("</textarea>\n					<br />\n					")
_e("If you want to limit site registrations to certain domains. One domain per line.")
print("				</td>\n			</tr>\n\n			<tr valign="top">\n				<th scope="row"><label for="banned_email_domains">")
_e("Banned Email Domains")
print("</label></th>\n				<td>\n					<textarea name="banned_email_domains" id="banned_email_domains" cols="45" rows="5">\n")
print(esc_textarea("" if get_site_option("banned_email_domains")=="" else implode("\n", get_site_option("banned_email_domains"))))
print("</textarea>\n					<br />\n					")
_e("If you want to ban domains from site registrations. One domain per line.")
print("				</td>\n			</tr>\n\n		</table>\n		<h3>")
_e("New Site Settings")
print("</h3>\n		<table class="form-table">\n\n			<tr valign="top">\n				<th scope="row"><label for="welcome_email">")
_e("Welcome Email")
print("</label></th>\n				<td>\n					<textarea name="welcome_email" id="welcome_email" rows="5" cols="45" class="large-text">\n")
print(esc_textarea(stripslashes(get_site_option("welcome_email"))))
print("</textarea>\n					<br />\n					")
_e("The welcome email sent to new site owners.")
print("				</td>\n			</tr>\n			<tr valign="top">\n				<th scope="row"><label for="welcome_user_email">")
_e("Welcome User Email")
print("</label></th>\n				<td>\n					<textarea name="welcome_user_email" id="welcome_user_email" rows="5" cols="45" class="large-text">\n")
print(esc_textarea(stripslashes(get_site_option("welcome_user_email"))))
print("</textarea>\n					<br />\n					")
_e("The welcome email sent to new users.")
print("				</td>\n			</tr>\n			<tr valign="top">\n				<th scope="row"><label for="first_post">")
_e("First Post")
print("</label></th>\n				<td>\n					<textarea name="first_post" id="first_post" rows="5" cols="45" class="large-text">\n")
print(esc_textarea(stripslashes(get_site_option("first_post"))))
print("</textarea>\n					<br />\n					")
_e("The first post on a new site.")
print("				</td>\n			</tr>\n			<tr valign="top">\n				<th scope="row"><label for="first_page">")
_e("First Page")
print("</label></th>\n				<td>\n					<textarea name="first_page" id="first_page" rows="5" cols="45" class="large-text">\n")
print(esc_textarea(stripslashes(get_site_option("first_page"))))
print("</textarea>\n					<br />\n					")
_e("The first page on a new site.")
print("				</td>\n			</tr>\n			<tr valign="top">\n				<th scope="row"><label for="first_comment">")
_e("First Comment")
print("</label></th>\n				<td>\n					<textarea name="first_comment" id="first_comment" rows="5" cols="45" class="large-text">\n")
print(esc_textarea(stripslashes(get_site_option("first_comment"))))
print("</textarea>\n					<br />\n					")
_e("The first comment on a new site.")
print("				</td>\n			</tr>\n			<tr valign="top">\n				<th scope="row"><label for="first_comment_author">")
_e("First Comment Author")
print("</label></th>\n				<td>\n					<input type="text" size="40" name="first_comment_author" id="first_comment_author" value="")
print(get_site_option("first_comment_author"))
print("" />\n					<br />\n					")
_e("The author of the first comment on a new site.")
print("				</td>\n			</tr>\n			<tr valign="top">\n				<th scope="row"><label for="first_comment_url">")
_e("First Comment URL")
print("</label></th>\n				<td>\n					<input type="text" size="40" name="first_comment_url" id="first_comment_url" value="")
print(esc_attr(get_site_option("first_comment_url")))
print("" />\n					<br />\n					")
_e("The URL for the first comment on a new site.")
print("				</td>\n			</tr>\n		</table>\n		<h3>")
_e("Upload Settings")
print("</h3>\n		<table class="form-table">\n			<tr valign="top">\n				<th scope="row">")
_e("Site upload space")
print("</th>\n				<td>\n				<label><input type="checkbox" id="upload_space_check_disabled" name="upload_space_check_disabled" value="0"")
checked(get_site_option("upload_space_check_disabled"), 0)
print("/> ")
printf(__("Limit total size of files uploaded to %s MB"), "</label><label><input name="blog_upload_space" type="number" min="0" style="width: 100px" id="blog_upload_space" value=""+esc_attr(get_site_option("blog_upload_space", 100))+"" />")
print("</label><br />\n				</td>\n			</tr>\n\n			<tr valign="top">\n				<th scope="row"><label for="upload_filetypes">")
_e("Upload file types")
print("</label></th>\n				<td><input name="upload_filetypes" type="text" id="upload_filetypes" class="large-text" value="")
print(esc_attr(get_site_option("upload_filetypes", "jpg jpeg png gif")))
print("" size="45" /></td>\n			</tr>\n\n			<tr valign="top">\n				<th scope="row"><label for="fileupload_maxk">")
_e("Max upload file size")
print("</label></th>\n				<td>")
printf(_x("%s KB", "File size in kilobytes"), "<input name="fileupload_maxk" type="number" min="0" style="width: 100px" id="fileupload_maxk" value=""+esc_attr(get_site_option("fileupload_maxk", 300))+"" />")
print("</td>\n			</tr>\n		</table>\n\n")
languages = get_available_languages()
if !empty(languages):
  lang = get_site_option("WPLANG")
  print("		<h3>")
  _e("Language Settings")
  print("</h3>\n		<table class="form-table">\n				<tr valign="top">\n					<th><label for="WPLANG">")
  _e("Default Language")
  print("</label></th>\n					<td>\n						<select name="WPLANG" id="WPLANG">\n							")
  mu_dropdown_languages(languages, get_site_option("WPLANG"))
  print("						</select>\n					</td>\n				</tr>\n		</table>\n")
print("\n		<h3>")
_e("Menu Settings")
print("</h3>\n		<table id="menu" class="form-table">\n			<tr valign="top">\n				<th scope="row">")
_e("Enable administration menus")
print("</th>\n				<td>\n			")
menu_perms = get_site_option("menu_items")
menu_items = apply_filters("mu_menu_items", {"plugins":__("Plugins")})
for val in menu_items:
  print("<label><input type='checkbox' name='menu_items["+key+"]' value='1'"+checked(menu_perms[key], "1", False) if isset(menu_perms[key]) else ""+" /> "+esc_html(val)+"</label><br/>")
print("				</td>\n			</tr>\n		</table>\n\n		")
do_action("wpmu_options")
print("\n\n		")
submit_button()
print("	</form>\n</div>\n\n")
include("../admin-footer.php")
