#!/usr/bin/python
#-*- coding: utf-8 -*-
define("WPINC", "wp-includes")
require(ABSPATH+WPINC+"/load.php")
require(ABSPATH+WPINC+"/default-constants.php")
require(ABSPATH+WPINC+"/version.php")
wp_initial_constants()
wp_check_php_mysql_versions()
ini_set("magic_quotes_runtime", 0)
ini_set("magic_quotes_sybase", 0)
date_default_timezone_set("UTC")
wp_unregister_GLOBALS()
wp_fix_server_vars()
wp_favicon_request()
wp_maintenance()
timer_start()
wp_debug_mode()
if WP_CACHE:
  include(WP_CONTENT_DIR+"/advanced-cache.php") if WP_DEBUG else include(WP_CONTENT_DIR+"/advanced-cache.php")
wp_set_lang_dir()
require(ABSPATH+WPINC+"/compat.php")
require(ABSPATH+WPINC+"/functions.php")
require(ABSPATH+WPINC+"/class-wp.php")
require(ABSPATH+WPINC+"/class-wp-error.php")
require(ABSPATH+WPINC+"/plugin.php")
require(ABSPATH+WPINC+"/pomo/mo.php")
require_wp_db()
GLOBALS["table_prefix"] = table_prefix
wp_set_wpdb_vars()
wp_start_object_cache()
require(ABSPATH+WPINC+"/default-filters.php")
if is_multisite():
  require(ABSPATH+WPINC+"/ms-blogs.php")
  require(ABSPATH+WPINC+"/ms-settings.php")
elif !defined("MULTISITE"):
  define("MULTISITE", False)
register_shutdown_function("shutdown_action_hook")
if SHORTINIT:
  return False
require_once(ABSPATH+WPINC+"/l10n.php")
wp_not_installed()
require(ABSPATH+WPINC+"/class-wp-walker.php")
require(ABSPATH+WPINC+"/class-wp-ajax-response.php")
require(ABSPATH+WPINC+"/formatting.php")
require(ABSPATH+WPINC+"/capabilities.php")
require(ABSPATH+WPINC+"/query.php")
require(ABSPATH+WPINC+"/theme.php")
require(ABSPATH+WPINC+"/class-wp-theme.php")
require(ABSPATH+WPINC+"/template.php")
require(ABSPATH+WPINC+"/user.php")
require(ABSPATH+WPINC+"/meta.php")
require(ABSPATH+WPINC+"/general-template.php")
require(ABSPATH+WPINC+"/link-template.php")
require(ABSPATH+WPINC+"/author-template.php")
require(ABSPATH+WPINC+"/post.php")
require(ABSPATH+WPINC+"/post-template.php")
require(ABSPATH+WPINC+"/post-thumbnail-template.php")
require(ABSPATH+WPINC+"/category.php")
require(ABSPATH+WPINC+"/category-template.php")
require(ABSPATH+WPINC+"/comment.php")
require(ABSPATH+WPINC+"/comment-template.php")
require(ABSPATH+WPINC+"/rewrite.php")
require(ABSPATH+WPINC+"/feed.php")
require(ABSPATH+WPINC+"/bookmark.php")
require(ABSPATH+WPINC+"/bookmark-template.php")
require(ABSPATH+WPINC+"/kses.php")
require(ABSPATH+WPINC+"/cron.php")
require(ABSPATH+WPINC+"/deprecated.php")
require(ABSPATH+WPINC+"/script-loader.php")
require(ABSPATH+WPINC+"/taxonomy.php")
require(ABSPATH+WPINC+"/update.php")
require(ABSPATH+WPINC+"/canonical.php")
require(ABSPATH+WPINC+"/shortcodes.php")
require(ABSPATH+WPINC+"/class-wp-embed.php")
require(ABSPATH+WPINC+"/media.php")
require(ABSPATH+WPINC+"/http.php")
require(ABSPATH+WPINC+"/class-http.php")
require(ABSPATH+WPINC+"/widgets.php")
require(ABSPATH+WPINC+"/nav-menu.php")
require(ABSPATH+WPINC+"/nav-menu-template.php")
require(ABSPATH+WPINC+"/admin-bar.php")
if is_multisite():
  require(ABSPATH+WPINC+"/ms-functions.php")
  require(ABSPATH+WPINC+"/ms-default-filters.php")
  require(ABSPATH+WPINC+"/ms-deprecated.php")
wp_plugin_directory_constants()
for mu_plugin in :
  include_once(mu_plugin)
unset(mu_plugin)
if is_multisite():
  for network_plugin in :
    include_once(network_plugin)
  unset(network_plugin)
do_action("muplugins_loaded")
if is_multisite():
  ms_cookie_constants()
wp_cookie_constants()
wp_ssl_constants()
require(ABSPATH+WPINC+"/vars.php")
create_initial_taxonomies()
create_initial_post_types()
register_theme_directory(get_theme_root())
for plugin in :
  include_once(plugin)
unset(plugin)
require(ABSPATH+WPINC+"/pluggable.php")
require(ABSPATH+WPINC+"/pluggable-deprecated.php")
wp_set_internal_encoding()
if WP_CACHE&&function_exists("wp_cache_postload"):
  wp_cache_postload()
do_action("plugins_loaded")
wp_functionality_constants()
wp_magic_quotes()
do_action("sanitize_comment_cookies")
wp_the_query = WP_Query()
wp_query = wp_the_query
GLOBALS["wp_rewrite"] = WP_Rewrite()
wp = WP()
GLOBALS["wp_widget_factory"] = WP_Widget_Factory()
GLOBALS["wp_roles"] = WP_Roles()
do_action("setup_theme")
wp_templating_constants()
load_default_textdomain()
locale = get_locale()
locale_file = WP_LANG_DIR+"/"+locale+".php"
if 0===validate_file(locale)&&is_readable(locale_file):
  require(locale_file)
unset(locale_file)
require_once(ABSPATH+WPINC+"/locale.php")
GLOBALS["wp_locale"] = WP_Locale()
if !defined("WP_INSTALLING")||"wp-activate.php"===pagenow:
  if TEMPLATEPATH!==STYLESHEETPATH&&file_exists(STYLESHEETPATH+"/functions.php"):
    include(STYLESHEETPATH+"/functions.php")
  if file_exists(TEMPLATEPATH+"/functions.php"):
    include(TEMPLATEPATH+"/functions.php")
do_action("after_setup_theme")
wp.init()
do_action("init")
if is_multisite():
  if True!==file = ms_site_check():
    require(file)
    die(0)
  unset(file)
do_action("wp_loaded")
