#!/usr/bin/python
#-*- coding: utf-8 -*-
get_header()
print("\n	<section id="primary" class="site-content">\n		<div id="content" role="main">\n\n		")
if have_posts():
  print("\n			")
  the_post()
  print("\n			<header class="archive-header">\n				<h1 class="archive-title">")
  printf(__("Author Archives: %s", "twentytwelve"), "<span class="vcard"><a class="url fn n" href=""+esc_url(get_author_posts_url(get_the_author_meta("ID")))+"" title=""+esc_attr(get_the_author())+"" rel="me">"+get_the_author()+"</a></span>")
  print("</h1>\n			</header><!-- .archive-header -->\n\n			")
  rewind_posts()
  print("\n			")
  twentytwelve_content_nav("nav-above")
  print("\n			")
  if get_the_author_meta("description"):
    print("			<div class="author-info">\n				<div class="author-avatar">\n					")
    print(get_avatar(get_the_author_meta("user_email"), apply_filters("twentytwelve_author_bio_avatar_size", 60)))
    print("				</div><!-- .author-avatar -->\n				<div class="author-description">\n					<h2>")
    printf(__("About %s", "twentytwelve"), get_the_author())
    print("</h2>\n					<p>")
    the_author_meta("description")
    print("</p>\n				</div><!-- .author-description	-->\n			</div><!-- .author-info -->\n			")
  print("\n			")
  print("			")
  while :
    the_post()
    print("				")
    get_template_part("content", get_post_format())
    print("			")
  print("\n			")
  twentytwelve_content_nav("nav-below")
  print("\n		")
else:
  print("			")
  get_template_part("content", "none")
  print("		")
print("\n		</div><!-- #content -->\n	</section><!-- #primary -->\n\n")
get_sidebar()
get_footer()
