#!/usr/bin/python
#-*- coding: utf-8 -*-
print("\n	<article id="post-")
the_ID()
print("" ")
post_class()
print(">\n		")
if is_sticky()&&is_home()&&!is_paged():
  print("		<div class="featured-post">\n			")
  _e("Featured post", "twentytwelve")
  print("		</div>\n		")
print("		<header class="entry-header">\n			")
the_post_thumbnail()
print("			")
if is_single():
  print("			<h1 class="entry-title">")
  the_title()
  print("</h1>\n			")
else:
  print("			<h1 class="entry-title">\n				<a href="")
  the_permalink()
  print("" title="")
  print(esc_attr(sprintf(__("Permalink to %s", "twentytwelve"), the_title_attribute("echo=0"))))
  print("" rel="bookmark">")
  the_title()
  print("</a>\n			</h1>\n			")
print("\n			")
if comments_open():
  print("				<div class="comments-link">\n					")
  comments_popup_link("<span class="leave-reply">"+__("Leave a reply", "twentytwelve")+"</span>", __("1 Reply", "twentytwelve"), __("% Replies", "twentytwelve"))
  print("				</div><!-- .comments-link -->\n			")
print("\n		</header><!-- .entry-header -->\n\n		")
if is_search():
  print("\n		<div class="entry-summary">\n			")
  the_excerpt()
  print("		</div><!-- .entry-summary -->\n		")
else:
  print("		<div class="entry-content">\n			")
  the_content(__("Continue reading <span class="meta-nav">&rarr;</span>", "twentytwelve"))
  print("			")
  wp_link_pages({"before":"<div class="page-links">"+__("Pages:", "twentytwelve"), "after":"</div>"})
  print("		</div><!-- .entry-content -->\n		")
print("\n		<footer class="entry-meta">\n			")
twentytwelve_entry_meta()
print("			")
edit_post_link(__("Edit", "twentytwelve"), "<span class="edit-link">", "</span>")
print("			")
if is_singular()&&get_the_author_meta("description")&&is_multi_author():
  print("\n				<div class="author-info">\n					<div class="author-avatar">\n						")
  print(get_avatar(get_the_author_meta("user_email"), apply_filters("twentytwelve_author_bio_avatar_size", 68)))
  print("					</div><!-- .author-avatar -->\n					<div class="author-description">\n						<h2>")
  printf(__("About %s", "twentytwelve"), get_the_author())
  print("</h2>\n						<p>")
  the_author_meta("description")
  print("</p>\n						<div class="author-link">\n							<a href="")
  print(esc_url(get_author_posts_url(get_the_author_meta("ID"))))
  print("" rel="author">\n								")
  printf(__("View all posts by %s <span class="meta-nav">&rarr;</span>", "twentytwelve"), get_the_author())
  print("							</a>\n						</div><!-- .author-link	-->\n					</div><!-- .author-description -->\n				</div><!-- .author-info -->\n			")
print("		</footer><!-- .entry-meta -->\n	</article><!-- #post -->\n")
