#!/usr/bin/python
#-*- coding: utf-8 -*-
print("<!DOCTYPE html>\n<!--[if IE 7]>\n<html class="ie ie7" ")
language_attributes()
print(">\n<![endif]-->\n<!--[if IE 8]>\n<html class="ie ie8" ")
language_attributes()
print(">\n<![endif]-->\n<!--[if !(IE 7) | !(IE 8)  ]><!-->\n<html ")
language_attributes()
print(">\n<!--<![endif]-->\n<head>\n<meta charset="")
bloginfo("charset")
print("" />\n<meta name="viewport" content="width=device-width" />\n<title>")
wp_title("|", True, "right")
print("</title>\n<link rel="profile" href="http://gmpg.org/xfn/11" />\n<link rel="pingback" href="")
bloginfo("pingback_url")
print("" />\n")
print("\n<!--[if lt IE 9]>\n<script src="")
print(get_template_directory_uri())
print("/js/html5.js" type="text/javascript"></script>\n<![endif]-->\n")
wp_head()
print("</head>\n\n<body ")
body_class()
print(">\n<div id="page" class="hfeed site">\n	<header id="masthead" class="site-header" role="banner">\n		<hgroup>\n			<h1 class="site-title"><a href="")
print(esc_url(home_url("/")))
print("" title="")
print(esc_attr(get_bloginfo("name", "display")))
print("" rel="home">")
bloginfo("name")
print("</a></h1>\n			<h2 class="site-description">")
bloginfo("description")
print("</h2>\n		</hgroup>\n\n		<nav id="site-navigation" class="main-navigation" role="navigation">\n			<h3 class="menu-toggle">")
_e("Menu", "twentytwelve")
print("</h3>\n			<a class="assistive-text" href="#content" title="")
esc_attr_e("Skip to content", "twentytwelve")
print("">")
_e("Skip to content", "twentytwelve")
print("</a>\n			")
wp_nav_menu({"theme_location":"primary", "menu_class":"nav-menu"})
print("		</nav><!-- #site-navigation -->\n\n		")
header_image = get_header_image()
if !empty(header_image):
  print("			<a href="")
  print(esc_url(home_url("/")))
  print(""><img src="")
  print(esc_url(header_image))
  print("" class="header-image" width="")
  print(width)
  print("" height="")
  print(height)
  print("" alt="" /></a>\n		")
print("	</header><!-- #masthead -->\n\n	<div id="main" class="wrapper">")
