#!/usr/bin/python
#-*- coding: utf-8 -*-
header("Content-Type: "+feed_content_type("atom")+"; charset="+get_option("blog_charset"), True)
more = 1
print("<?xml version="1.0" encoding=""+get_option("blog_charset")+""?"+">")
print("<feed\n  xmlns="http://www.w3.org/2005/Atom"\n  xmlns:thr="http://purl.org/syndication/thread/1.0"\n  xml:lang="")
bloginfo_rss("language")
print(""\n  xml:base="")
bloginfo_rss("url")
print("/wp-atom.php"\n  ")
do_action("atom_ns")
print(" >\n	<title type="text">")
bloginfo_rss("name")
wp_title_rss()
print("</title>\n	<subtitle type="text">")
bloginfo_rss("description")
print("</subtitle>\n\n	<updated>")
print(mysql2date("Y-m-d\TH:i:s\Z", get_lastpostmodified("GMT"), False))
print("</updated>\n\n	<link rel="alternate" type="")
bloginfo_rss("html_type")
print("" href="")
bloginfo_rss("url")
print("" />\n	<id>")
bloginfo("atom_url")
print("</id>\n	<link rel="self" type="application/atom+xml" href="")
self_link()
print("" />\n\n	")
do_action("atom_head")
print("	")
while :
  the_post()
  print("	<entry>\n		<author>\n			<name>")
  the_author()
  print("</name>\n			")
  author_url = get_the_author_meta("url")
  if !empty(author_url):
    print("			<uri>")
    the_author_meta("url")
    print("</uri>\n			")
  do_action("atom_author")
  print("		</author>\n		<title type="")
  html_type_rss()
  print(""><![CDATA[")
  the_title_rss()
  print("]]></title>\n		<link rel="alternate" type="")
  bloginfo_rss("html_type")
  print("" href="")
  the_permalink_rss()
  print("" />\n		<id>")
  the_guid()
  print("</id>\n		<updated>")
  print(get_post_modified_time("Y-m-d\TH:i:s\Z", True))
  print("</updated>\n		<published>")
  print(get_post_time("Y-m-d\TH:i:s\Z", True))
  print("</published>\n		")
  the_category_rss("atom")
  print("		<summary type="")
  html_type_rss()
  print(""><![CDATA[")
  the_excerpt_rss()
  print("]]></summary>\n")
  if !get_option("rss_use_excerpt"):
    print("		<content type="")
    html_type_rss()
    print("" xml:base="")
    the_permalink_rss()
    print(""><![CDATA[")
    the_content_feed("atom")
    print("]]></content>\n")
  atom_enclosure()
  do_action("atom_entry")
  print("		<link rel="replies" type="")
  bloginfo_rss("html_type")
  print("" href="")
  the_permalink_rss()
  print("#comments" thr:count="")
  print(get_comments_number())
  print(""/>\n		<link rel="replies" type="application/atom+xml" href="")
  print(esc_url(get_post_comments_feed_link(0, "atom")))
  print("" thr:count="")
  print(get_comments_number())
  print(""/>\n		<thr:total>")
  print(get_comments_number())
  print("</thr:total>\n	</entry>\n	")
print("</feed>\n")
